### PR TITLE
Return early if a valid contrast ratio is not possible

### LINKED ISSUE #25: Contrast method fails for some colors
> https://runkit.com/cdonohue/599dca37c848f6001260c77f

### PR DESCRIPTION
**Pull request by cdonohue**
Fixes #25

### CODE REVIEW

File: src/contrast.js [hunk 1]
```diff
@@ -1,11 +1,14 @@
 import parse from "./parse";
 import relativeLuminance from "./relativeLuminance";
+import { darken, lighten } from "./lightness";
 
 const contrast = (color, dark = parse("#000"), light = parse("#FFF")) => {
   const baseColor = parse(color);
   const darkColor = typeof dark === "string" ? parse(dark) : dark;
   const lightColor = typeof light === "string" ? parse(light) : light;
 
+  console.log(baseColor.luma < 128);
```
Comment (prestonvanloon) [inline src/contrast.js:10]: Is this intentional?

**Comment by prestonvanloon** [comment]
Where's the regression test?

File: src/contrast.js (hunk 1 above)
Comment (cdonohue) [reply src/contrast.js:10]: Nope, that was left in there by mistake @prestonvanloon. I've since corrected it 😄 . This needs to be revisited with more tests, hence the added `TODO` when the above `console.log` was removed.

Comment (cdonohue) [reply src/contrast.js:10]: Also, this was a quick fix in order to ship another PR of ours that relies on `polychrome`

Comment (cdonohue) [reply src/contrast.js:10]: Not that that's ever an excuse for skipping a test 😬 😳
